* BRAT-FAQ := BRAT Rapid Annotation Tool - Frequently Asked Questions
** What does BRAT stands for?
[[https://github.com/nlplab/brat][BRAT]] is a recursive acronym for BRAT Rapid Annotation Tool
** How do I quickly check it out?
Try it [[http://weaver.nlplab.org/~brat/demo/latest/#/][online here]] without installing!
Else download, install in standalone mode and run as follows:
#+BEGIN_SRC sh
# download BRAT
wget http://weaver.nlplab.org/~brat/releases/brat-v1.3_Crunchy_Frog.tar.gz
# extract BRAT
tar xzf brat-v1.3_Cruncy_Frog.tar.gz
# install it for standalone mode if not done already
# the installation asks for username and password to access brat
# give something simple admin admin123 root@localhost
cd brat-v1.3_Cruncy_Frog/
./install.sh -u
# when done, run the standalone server by giving optional <PORT_NUMBER> as follows
# NOTE: Default <PORT_NUMBER> is 8001
python standalone.py <PORT_NUMBER>
# now point your browser to http://localhost:<PORT_NUMBER>
open http://localhost:8001
#+END_SRC
** How do I access BRAT for lrsl-data on Gaius?
Just point your browser at [[http://gaius.isri.cmu.edu:8300/brat][Gaius]].

Administrivia can be directed to me or Travis.
** How do I create data sources for lrsl-data on Gaius?
Simply copy over your data files as plain text.
NOTE: Currently, you need to create empty .ann files for your data sources.
#+BEGIN_SRC sh
# Sample data creation process example
mkdir sudhi_data
cp /path/to/text_for_annotation.txt sudhi_data
# XXX: Create assoicated .ann file for each .txt file
# Example for just one file:
touch sudhi_data/text_for_annotation.ann
# Copy the directory to Gaius.
# Supply $USER and $GAIUS_HOSTNAME appropriately.
scp -r sudhi_data ${USER}@${GAIUS_HOSTNAME}:/var/www/brat/data/
# Make sure apache can read and write your files by issusing following:
# Of course, replace $USER and $GAIUS_HOSTNAME appropriately.
ssh ${USER}@${GAIUS_HOSTNAME} "chown -R $USER:www-data /var/www/brat/data/sudhi_data"
#+END_SRC
** Is there a tutorial I can learn from?
Yes! The BRAT comes with its own tutorial. Yes, just open BRAT, sign in and
browse data/tutorial/news/000-introduction or [[https://gaius.isri.cmu.edu:8300/brat/index.xhtml#/tutorials/news/000-introduction][click here]] for the online version.
** Can I modify .ann files directly?
Yes you may! The annotations are saved in the [[http://brat.nlplab.org/standoff.html][standoff format explained here]].
The format comes from the [[http://2011.bionlp-st.org/home/file-formats][BioNLP community]].
** How do I configure my annotation labels?
You can define per project annotation configuration in your project directory.
The sample configuration file in ~data/tutorial/annotation.conf~ is well
commented. You can read more [[http://brat.nlplab.org/configuration.html#annotation-configuration][here]].
The configuration is stored in ~annotation.conf~ file. Here's an example:
#+BEGIN_SRC configuration
# cat /var/www/brat/data/sudhi_data/annotation.conf
[entities]
ENTITY_LABEL1
ENTITY_LABEL2
ENTITY_LABEL3
EVENT_LABEL1
[relations]
RELATION1 Arg1:LABEL1, Arg2:LABEL2
[events]
EVENT1 LABEL1_Arg{2}:LABEL1, LABEL2_Arg?:LABEL2
[attributes]
# TODO
#+END_SRC
** How do I configure shortcuts to rapidly annotate my document?
Simply create ~kb_shortcuts.conf~ in your project and associate ~ENTITY_LABELS~
with keyboard strokes. For example:
#+BEGIN_SRC conf
# Keyborad configuration for project sudhi_data
a LABEL_A
b LABEL_B
c LABEL_C
#+END_SRC
Now when you select text in BRAT, you can press ~b<ENTER>~ (that's ~b~ followed
by the ~ENTER~ key) to quickly annotate the selected text with label ~LABEL_B~.
